### ISSUE TITLE
Error Running Module

### ISSUE THREAD

**Issue by gil--** [sdepold/contentful-ghost-importer#69]
Not sure if this importer still works but I'm having trouble running it. I'm using the following command:

```shell
contentful-ghost-importer -b example.com -s <spaceId> -t <cmaToken> ./ghost.json
```

```log
/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/data-mapper.js:76
  return markdown.replace(/\!\[(.*?)\]\((\/.*?)\)/g, function (match, title, reference) {
                 ^

TypeError: Cannot read property 'replace' of undefined
    at extendEmbeddedReferences (/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/data-mapper.js:62:10)
    at /Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/data-mapper.js:24:16
    at Array.map (native)
    at mapPosts (/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/data-mapper.js:23:16)
    at mapData (/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/data-mapper.js:8:12)
    at Object.run (/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/src/contentful-ghost-importer.js:11:20)
    at Object.<anonymous> (/Users/gil/.nvm/versions/node/v8.0.0/lib/node_modules/contentful-ghost-importer/bin/contentful-ghost-importer:29:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Is the latest export potentially not compatible?

**Comment by gil--** [comment]
got it all to work but had to make some changes to the source. will try to create PR.

**Comment by wanderingcrow** [comment]
I had the same error. I'm assuming this repo is no longer functional/maintained?
